[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "1.0.0"
authors = ["Fabelis <contact@fabelis.ai>"]
license = "Apache-2.0"
repository = "https://github.com/fabelis/mcp-rig"
description = "MCP Tech"
